version: '3.0'
services:
  database:
    image: mysql:5.7
    volumes:
      - database_data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: dockerdb
      MYSQL_USER: dockeruser
      MYSQL_PASSWORD: dockerpass

  storage:
    image: salsify/fakes3
    volumes:
      - storage_data:/var/data/fakes3:delegated
    ports:
      - 4554:80
    command:  >
      bash -c "mkdir /var/data/fakes3/cg_bucket &&
      /opt/fakes3/bin/fakes3 -r /var/data/fakes3 -p 80"
  web:
    build: .docker
    ports:
      - 8080:80
    volumes:
      - .:/var/www/:delegated
    command: "/var/www/.docker/startup"
    environment:
      CF_INSTANCE_INDEX: '0'
      VCAP_APPLICATION: >
        {"name": "web"}
      VCAP_SERVICES: >
        { "aws-rds": [{
            "name": "database",
            "credentials": {
              "db_name": "dockerdb",
              "host": "database",
              "password": "dockerpass",
              "port": "3306",
              "username": "dockeruser"
            }
          }],
          "user-provided": [{
            "name": "secrets",
            "credentials": {
              "ADMIN_EMAIL": "secret@example.com",
              "CRON_KEY": "SECRET",
              "HASH_SALT": "SECRET",
              "ROOT_USER_NAME": "root",
              "ROOT_USER_PASS": "root"
            }
          }],
          "s3": [{
            "name": "storage",
            "credentials": {
              "access_key_id": "ACCESS_KEY_ID",
              "bucket": "cg-bucket",
              "region": "us-west-1",
              "secret_access_key": "secret",
              "uri": "s3://ACCESS_KEY_ID:secret@storage/cg-bucket"
            },
            "label": "s3",
            "plan": "basic-public"
           }]
        }
    depends_on:
      - database
      - storage
volumes:
  database_data:
  storage_data:
