version: '3.0'
services:
  database:
    image: mysql:5.7
    volumes:
      - database_data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
  web:
    build: .docker
    ports:
      - 8080:80
    volumes:
      - .:/var/www/:delegated
    command: "/var/www/.docker/startup"
    environment:
      CF_INSTANCE_INDEX: '0'
      VCAP_APPLICATION: >
        {"name": "osc-web", "application_id": "docker"}
      VCAP_SERVICES: >
        { "aws-rds": [{
            "name": "osc-database",
            "credentials": {
              "db_name": "drupal",
              "host": "database",
              "password": "mysql",
              "port": "3306",
              "username": "root"
            }
          }],
          "user-provided": [{
            "name": "osc-secrets",
            "credentials": {
              "ADMIN_EMAIL": "secret@example.com",
              "CRON_KEY": "SECRET",
              "HASH_SALT": "SECRET",
              "ROOT_USER_NAME": "root",
              "ROOT_USER_PASS": "root"
            }
          }]
        }
    depends_on:
      - database
volumes:
  database_data:
