features:
  node_user_picture: 0
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 0
logo:
  use_default: 1
favicon:
  use_default: 0
  path: ''
uswds_header_style: extended
uswds_header_mega: 0
uswds_search: 1
uswds_government_banner: 1
uswds_footer_style: big
uswds_footer_agency: 1
uswds_footer_agency_name: GSA
uswds_footer_agency_url: 'https://www.gsa.gov'
uswds_footer_agency_logo: footer-logo.png
uswds_contact_center: ''
uswds_email: ''
uswds_phone: 1-800-666-5555
uswds_facebook: 'https://www.facebook.com/gsa'
uswds_twitter: 'https://twitter.com/usgsa'
uswds_youtube: 'https://www.youtube.com/usgsa'
uswds_rss: 'https://www.gsa.gov/blog'
uswds_paragraphs_edge_to_edge: 1
uswds_menu_accordion_duplicate_parent: 0
uswds_menu_bypass:
  primary_menu: 0
  secondary_menu: 0
  mobile_menu: 0
  sidebar_first: 0
  footer_menu: 0
